In [11]:
import numpy as np

import sys

sys.path.append(r"C:\Users\mauro\Documents\projects\gsf")

from pygsf.orientations.orientations import Plane, Axis, Direct
from pygsf.mathematics.arrays import svd

In [3]:
plane1 = Plane(90, 0)
plane2 = Plane(90, 5)

# plane to xyz

n_axis_1 = plane1.normAxis()
n_axis_2 = plane2.normAxis()

normal_1 = n_axis_1.toXYZ()
normal_2 = n_axis_2.toXYZ()

print(normal_1)
print(normal_2)

xyzes = (normal_1, normal_2)

# pack tuples into array

a = np.stack(xyzes)
print(type(a))
print(a.shape)

# svd

res = svd(a)

"""
print(type(res))
for res_el in res:
    print(res_el)
"""

u = res[0]
s = res[1]
vh = res[2]

#print(vh)

print("mean", vh[0,:]) # mean value
print("girdle normal", vh[2, :]) # normal to girdle

(-6.123233995736766e-17, -1.1248198369963932e-32, -1.0)
(-0.08715574274765814, -1.6010250207484453e-17, -0.9961946980917455)
<class 'numpy.ndarray'>
(2, 3)
mean [4.36193874e-02 9.68544963e-18 9.99048222e-01]
girdle normal [-2.22044605e-16  1.00000000e+00  0.00000000e+00]


In [8]:
# axes to xyz

axis_1 = Axis.fromAzPl(270, 80)
axis_2 = Axis.fromAzPl(270, 90)
axis_3 = Axis.fromAzPl(90, 80)

print(axis_1)
print(axis_2)
print(axis_3)

xyz_1 = axis_1.toXYZ()
xyz_2 = axis_2.toXYZ()
xyz_3 = axis_3.toXYZ()

print(xyz_1)
print(xyz_2)
print(xyz_3)

xyzes = (xyz_1, xyz_2, xyz_3)

# pack tuples into array

a = np.stack(xyzes)
print(type(a))
print(a.shape)

# svd

res = svd(a)

u = res[0]
s = res[1]
vh = res[2]

print("\nu")
print(u)
print("\ns")
print(s)
print("\nvh")
print(vh)

print("\nmean", vh[0,:]) # mean value
print("\ngirdle normal", vh[2, :]) # normal to girdle



Axis(az: 270.00°, pl: 80.00°)
Axis(az: 270.00°, pl: 90.00°)
Axis(az: 90.00°, pl: 80.00°)
(-0.17364817766693041, -3.1898652743636585e-17, -0.984807753012208)
(-6.123233995736766e-17, -1.1248198369963932e-32, -1.0)
(0.17364817766693041, 1.0632884247878861e-17, -0.984807753012208)
<class 'numpy.ndarray'>
(3, 3)

u
[[-5.74381572e-01 -7.07106781e-01  4.12414609e-01]
 [-5.83242334e-01 -2.49342109e-16 -8.12298209e-01]
 [-5.74381572e-01  7.07106781e-01  4.12414609e-01]]

s
[1.71455318e+00 2.45575608e-01 8.29293425e-17]

vh
[[-0.00000000e+00  2.22044605e-16  1.00000000e+00]
 [ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -1.00000000e+00  0.00000000e+00]]

mean [-0.00000000e+00  2.22044605e-16  1.00000000e+00]

girdle normal [ 0. -1.  0.]


In [9]:
# axes to xyz

axis_1 = Axis.fromAzPl(270, 10)
axis_2 = Axis.fromAzPl(270, 0)
axis_3 = Axis.fromAzPl(90, 5)
axis_4 = Axis.fromAzPl(270, 3)

print(axis_1)
print(axis_2)
print(axis_3)
print(axis_4)

xyz_1 = axis_1.toXYZ()
xyz_2 = axis_2.toXYZ()
xyz_3 = axis_3.toXYZ()
xyz_4 = axis_3.toXYZ()

print(xyz_1)
print(xyz_2)
print(xyz_3)
print(xyz_4)


xyzes = (xyz_1, xyz_2, xyz_3, xyz_4)

# pack tuples into array

a = np.stack(xyzes)
print(type(a))
print(a.shape)

# svd

res = svd(a)

u = res[0]
s = res[1]
vh = res[2]

print("\nu")
print(u)
print("\ns")
print(s)
print("\nvh")
print(vh)

print("\nmean", vh[0,:]) # mean value
print("\ngirdle normal", vh[2, :]) # normal to girdle



Axis(az: 270.00°, pl: 10.00°)
Axis(az: 270.00°, pl: 0.00°)
Axis(az: 90.00°, pl: 5.00°)
Axis(az: 270.00°, pl: 3.00°)
(-0.984807753012208, -1.8090624937528466e-16, -0.17364817766693033)
(-1.0, -1.8369701987210297e-16, -0.0)
(0.9961946980917455, 6.099933241728101e-17, -0.08715574274765817)
(0.9961946980917455, 6.099933241728101e-17, -0.08715574274765817)
<class 'numpy.ndarray'>
(4, 3)

u
[[-4.95159748e-01  8.18593700e-01  2.91069028e-01  4.15006612e-17]
 [-5.02858220e-01  3.16906670e-03 -8.64363099e-01  8.45760385e-17]
 [ 5.00974268e-01  4.06136868e-01 -2.89961423e-01 -7.07106781e-01]
 [ 5.00974268e-01  4.06136868e-01 -2.89961423e-01  7.07106781e-01]]

s
[1.98863165e+00 2.12941674e-01 6.91035294e-17]

vh
[[ 9.99999772e-01  1.22189585e-16 -6.74826367e-04]
 [-6.74826367e-04 -4.44089210e-16 -9.99999772e-01]
 [-1.22489993e-16  1.00000000e+00 -4.44089210e-16]]

mean [ 9.99999772e-01  1.22189585e-16 -6.74826367e-04]

girdle normal [-1.22489993e-16  1.00000000e+00 -4.44089210e-16]


In [12]:
# directions to xyz

d_1 = Direct.fromAzPl(270, 10)
d_2 = Direct.fromAzPl(270, 5)
d_3 = Direct.fromAzPl(270, -5)
d_4 = Direct.fromAzPl(270, -10)

print(d_1)
print(d_2)
print(d_3)
print(d_4)

xyz_1 = d_1.toXYZ()
xyz_2 = d_2.toXYZ()
xyz_3 = d_3.toXYZ()
xyz_4 = d_3.toXYZ()

print(xyz_1)
print(xyz_2)
print(xyz_3)
print(xyz_4)


xyzes = (xyz_1, xyz_2, xyz_3, xyz_4)

# pack tuples into array

a = np.stack(xyzes)
print(type(a))
print(a.shape)

# svd

res = svd(a)

u = res[0]
s = res[1]
vh = res[2]

print("\nu")
print(u)
print("\ns")
print(s)
print("\nvh")
print(vh)

print("\nmean", vh[0,:]) # mean value
print("\ngirdle normal", vh[2, :]) # normal to girdle



Direct(az: 270.00°, pl: 10.00°)
Direct(az: 270.00°, pl: 5.00°)
Direct(az: 270.00°, pl: -5.00°)
Direct(az: 270.00°, pl: -10.00°)
(-0.984807753012208, -1.8090624937528466e-16, -0.17364817766693033)
(-0.9961946980917455, -1.82997997251843e-16, -0.08715574274765817)
(-0.9961946980917455, -1.82997997251843e-16, 0.08715574274765817)
(-0.9961946980917455, -1.82997997251843e-16, 0.08715574274765817)
<class 'numpy.ndarray'>
(4, 3)

u
[[-4.97353160e-01 -6.73727078e-01  5.46563499e-01  0.00000000e+00]
 [-5.02141728e-01 -2.90194111e-01 -8.14641678e-01 -1.18255833e-16]
 [-5.00246699e-01  4.80561756e-01  1.37162821e-01 -7.07106781e-01]
 [-5.00246699e-01  4.80561756e-01  1.37162821e-01  7.07106781e-01]]

s
[1.98717817e+00 2.26103766e-01 6.01588582e-19]

vh
[[ 9.99766614e-01  1.87350135e-16  2.16036290e-02]
 [-2.16036290e-02  8.65973959e-15  9.99766614e-01]
 [-0.00000000e+00  1.00000000e+00 -8.88178420e-15]]

mean [9.99766614e-01 1.87350135e-16 2.16036290e-02]

girdle normal [-0.0000000e+00  1.0000000

In [13]:
# directions to xyz

d_1 = Direct.fromAzPl(90, 10)
d_2 = Direct.fromAzPl(90, 5)
d_3 = Direct.fromAzPl(90, -5)
d_4 = Direct.fromAzPl(90, -10)

print(d_1)
print(d_2)
print(d_3)
print(d_4)

xyz_1 = d_1.toXYZ()
xyz_2 = d_2.toXYZ()
xyz_3 = d_3.toXYZ()
xyz_4 = d_3.toXYZ()

print(xyz_1)
print(xyz_2)
print(xyz_3)
print(xyz_4)


xyzes = (xyz_1, xyz_2, xyz_3, xyz_4)

# pack tuples into array

a = np.stack(xyzes)
print(type(a))
print(a.shape)

# svd

res = svd(a)

u = res[0]
s = res[1]
vh = res[2]

print("\nu")
print(u)
print("\ns")
print(s)
print("\nvh")
print(vh)

print("\nmean", vh[0,:]) # mean value
print("\ngirdle normal", vh[2, :]) # normal to girdle



Direct(az: 90.00°, pl: 10.00°)
Direct(az: 90.00°, pl: 5.00°)
Direct(az: 90.00°, pl: -5.00°)
Direct(az: 90.00°, pl: -10.00°)
(0.984807753012208, 6.030208312509488e-17, -0.17364817766693033)
(0.9961946980917455, 6.099933241728101e-17, -0.08715574274765817)
(0.9961946980917455, 6.099933241728101e-17, 0.08715574274765817)
(0.9961946980917455, 6.099933241728101e-17, 0.08715574274765817)
<class 'numpy.ndarray'>
(4, 3)

u
[[-4.97353160e-01 -6.73727078e-01  5.46563499e-01  0.00000000e+00]
 [-5.02141728e-01 -2.90194111e-01 -8.14641678e-01  1.18255833e-16]
 [-5.00246699e-01  4.80561756e-01  1.37162821e-01 -7.07106781e-01]
 [-5.00246699e-01  4.80561756e-01  1.37162821e-01  7.07106781e-01]]

s
[1.98717817e+00 2.26103766e-01 1.02693131e-18]

vh
[[-9.99766614e-01 -6.24500451e-17  2.16036290e-02]
 [ 2.16036290e-02 -2.88657986e-15  9.99766614e-01]
 [-0.00000000e+00 -1.00000000e+00 -3.10862447e-15]]

mean [-9.99766614e-01 -6.24500451e-17  2.16036290e-02]

girdle normal [-0.00000000e+00 -1.00000000e+00 