## Numpy gradients

In [27]:
import numpy as np

In [28]:
a= np.array([[1, 2, 3, 4], [4, 6, 8, 10], [9, 11, 13, 15]])

In [29]:
a

array([[ 1,  2,  3,  4],
       [ 4,  6,  8, 10],
       [ 9, 11, 13, 15]])

In [30]:
np.gradient(a, axis=0)  # along y axis

array([[3. , 4. , 5. , 6. ],
       [4. , 4.5, 5. , 5.5],
       [5. , 5. , 5. , 5. ]])

In [31]:
np.gradient(a, axis=1)  # along x axis

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

## Test pygsf gradients and directional derivative

In [32]:
from math import pi
from numpy import array

In [33]:
from pygsf.spatial.rasters.fields import *

In [34]:
fld1 = array([
   [1, 1, 1, 1],
   [1, 1, 1, 1],
   [1, 1, 1, 1]])

In [35]:
grad_j(fld1, cell_size_j=10)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
grad_i(fld1, cell_size_i=10)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
fld2 = array([
   [10, 10, 10, 10],
   [20, 20, 20, 20],
   [30, 30, 30, 30]])

In [38]:
grad_j(fld2, cell_size_j=10)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
grad_i(fld2, cell_size_i=10)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
dir_deriv(fld2, cell_size_x=10, cell_size_y=10, direct_rad=pi*45.0/180.0)

array([[-0.70710678, -0.70710678, -0.70710678, -0.70710678],
       [-0.70710678, -0.70710678, -0.70710678, -0.70710678],
       [-0.70710678, -0.70710678, -0.70710678, -0.70710678]])

In [41]:
dir_deriv(fld2, cell_size_x=10, cell_size_y=10, direct_rad=pi*0.0/180.0)

array([[-1., -1., -1., -1.],
       [-1., -1., -1., -1.],
       [-1., -1., -1., -1.]])

In [42]:
dir_deriv(fld2, cell_size_x=10, cell_size_y=10, direct_rad=pi*180.0/180.0)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
dir_deriv(fld2, cell_size_x=10, cell_size_y=10, direct_rad=pi*90.0/180.0)

array([[-6.123234e-17, -6.123234e-17, -6.123234e-17, -6.123234e-17],
       [-6.123234e-17, -6.123234e-17, -6.123234e-17, -6.123234e-17],
       [-6.123234e-17, -6.123234e-17, -6.123234e-17, -6.123234e-17]])

In [44]:
dir_deriv(fld2, cell_size_x=10, cell_size_y=10, direct_rad=pi*270.0/180.0)

array([[1.8369702e-16, 1.8369702e-16, 1.8369702e-16, 1.8369702e-16],
       [1.8369702e-16, 1.8369702e-16, 1.8369702e-16, 1.8369702e-16],
       [1.8369702e-16, 1.8369702e-16, 1.8369702e-16, 1.8369702e-16]])

In [45]:
dir_deriv(fld2, cell_size_x=10, cell_size_y=10, direct_rad=pi*315.0/180.0)

array([[-0.70710678, -0.70710678, -0.70710678, -0.70710678],
       [-0.70710678, -0.70710678, -0.70710678, -0.70710678],
       [-0.70710678, -0.70710678, -0.70710678, -0.70710678]])

In [46]:
dir_deriv(fld2, cell_size_x=10, cell_size_y=10, direct_rad=pi*135.0/180.0)

array([[0.70710678, 0.70710678, 0.70710678, 0.70710678],
       [0.70710678, 0.70710678, 0.70710678, 0.70710678],
       [0.70710678, 0.70710678, 0.70710678, 0.70710678]])

## Test pygsf orientations

In [47]:
fld3 = array([
   [10, 10, 10, 10],
   [20, 20, 20, 20],
   [30, 30, 30, 30]])

In [48]:
fld4 = fld3

In [49]:
orients_d(fld3, fld4)

array([[45., 45., 45., 45.],
       [45., 45., 45., 45.],
       [45., 45., 45., 45.]])

In [50]:
orients_d(fld3, -fld4)

array([[135., 135., 135., 135.],
       [135., 135., 135., 135.],
       [135., 135., 135., 135.]])

In [51]:
orients_d(-fld3, fld4)

array([[315., 315., 315., 315.],
       [315., 315., 315., 315.],
       [315., 315., 315., 315.]])

In [52]:
orients_d(-fld3, -fld4)

array([[225., 225., 225., 225.],
       [225., 225., 225., 225.],
       [225., 225., 225., 225.]])

In [53]:
orients_d(fld3, 0.0)

array([[90., 90., 90., 90.],
       [90., 90., 90., 90.],
       [90., 90., 90., 90.]])

In [54]:
orients_d(0, fld4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
orients_d(0, -fld4)

array([[180., 180., 180., 180.],
       [180., 180., 180., 180.],
       [180., 180., 180., 180.]])

In [56]:
orients_d(-fld3, 0.0)

array([[270., 270., 270., 270.],
       [270., 270., 270., 270.],
       [270., 270., 270., 270.]])